### ISSUE TITLE
请求接口返回口令无效

### ISSUE THREAD

**Issue by chiikin** [zsakvo/hbooker-extractor#11]
获取章节内容时返回口令无效，导致获取失败。

**Comment by chiikin** [comment]
get_chapter_cmd接口增加了对header 头User-Agent的校验。

**Comment by zsakvo** [comment]
没加吧……今天我还在搞另一个项目 （在线阅读那个），不增加 ua 也是可以拿到值的。
后续我准备把导出功能合到那边，这里 archive 掉好了。
说回 ua，据我观察，目前这个 ua 似乎只是关系到章节内图片的获取（不带移动标识会提示你版本低不支持图片）

**Comment by chiikin** [comment]
> 没加吧……今天我还在搞另一个项目 （在线阅读那个），不增加 ua 也是可以拿到值的。
> 后续我准备把导出功能合到那边，这里 archive 掉好了。
> 说回 ua，据我观察，目前这个 ua 似乎只是关系到章节内图片的获取（不带移动标识会提示你版本低不支持图片）

这个项目和cirno两个项目我都测试了，当获取章节内容的时候都提示口令失效。我测试过了增加移动的ua标志后get_chapter_cmd接口获取的cmd才能正确获取章节内容。而且我还测试了其他header对请求的影响，最终确认为ua。测试获取的章节包括免费章节和订阅章节（已订阅），都是只有设置了移动ua后口令才有效。

**Comment by zsakvo** [comment]
> > 没加吧……今天我还在搞另一个项目 （在线阅读那个），不增加 ua 也是可以拿到值的。
> > 后续我准备把导出功能合到那边，这里 archive 掉好了。
> > 说回 ua，据我观察，目前这个 ua 似乎只是关系到章节内图片的获取（不带移动标识会提示你版本低不支持图片）
> 
> 这个项目和 cirno 两个项目我都测试了，当获取章节内容的时候都提示口令失效。我测试过了增加移动的 ua 标志后 get_chapter_cmd 接口获取的 cmd 才能正确获取章节内容。而且我还测试了其他 header 对请求的影响，最终确认为 ua。测试获取的章节包括免费章节和订阅章节（已订阅），都是只有设置了移动 ua 后口令才有效。

Cirno-Server 里面我已经附加了 相关的标识（Android  包名），理论上说是用不到再自己追加了……
而且昨天在我的测试里面 ua 还会影响某些接口的返回值（两种情况分别返回数字和字符串）
不过由于这个写的比较早，没注意到 ua 问题，所以没加，后面的话应该都会追加上对应的 ua，倒也无妨。
