### ISSUE TITLE
一直停在【正在获取章节内容】

### ISSUE THREAD

**Issue by lumiamilk** [zsakvo/hbooker-extractor#12]
![捕获](https://user-images.githubusercontent.com/73302560/96944497-854b6100-150d-11eb-8538-2d88ad3d60df.PNG)
![捕获2](https://user-images.githubusercontent.com/73302560/96944503-85e3f780-150d-11eb-8144-915f677da972.PNG)
![捕获3](https://user-images.githubusercontent.com/73302560/96944506-867c8e00-150d-11eb-9f43-e870f091b2ad.PNG)
![捕获4](https://user-images.githubusercontent.com/73302560/96944507-87152480-150d-11eb-8c64-92db1b48969a.PNG)
![捕获5](https://user-images.githubusercontent.com/73302560/96944509-87152480-150d-11eb-892d-53a6313eb907.PNG)
![捕获6](https://user-images.githubusercontent.com/73302560/96944510-87adbb00-150d-11eb-8cba-ad2263b5888c.PNG)
![捕获7](https://user-images.githubusercontent.com/73302560/96944511-88465180-150d-11eb-9bfb-71ef46734740.PNG)
![捕获8](https://user-images.githubusercontent.com/73302560/96944514-88465180-150d-11eb-89e2-36ce7b38321c.PNG)

**Comment by zsakvo** [comment]
本仓库准备废弃，全新构建的版本在此，谢谢合作。
https://github.com/zsakvo/Cirno-go
