### ISSUE TITLE
Module Error  eslint-loader  Unexpected console

### ISSUE THREAD

**Issue by jerryfangr** [zsakvo/hbooker-extractor#14]
老哥开了eslint后，你忘记注释console.log
yarn build 会直接出错。

console分别出现在以下几行，
at src\views\Home.vue:61
at src\views\Home.vue:75
at src\views\Home.vue:199
at src\views\Home.vue:311

**Comment by zsakvo** [comment]
啊 感谢，不过这个仓库其实几乎废弃了……
我另写了个 go 版本的，更好用一些 :)

**Comment by jerryfangr** [comment]
> 啊 感谢，不过这个仓库其实几乎废弃了……
> 我另写了个 go 版本的，更好用一些 :)

是不是Cirno-go啊，readme下有个错别字。

Features
Cache iamages in chapters  -> Cache images

**Comment by zsakvo** [comment]
是这个  总之非常感谢~
