### ISSUE TITLE
【正在获取章节内容】时出现问题

### ISSUE THREAD

**Issue by chenshunji** [zsakvo/hbooker-extractor#5]
![火狐截图_2020-08-06T05-13-35 672Z](https://user-images.githubusercontent.com/20376895/89493465-ce312a80-d7e6-11ea-8f7e-b2f5957568f8.png)

你好，我在登陆的时候都么有问题，只是【正在获取章节内容】的时候就卡住不动了，请问这是什么原因？

**Comment by zsakvo** [comment]
网页右键，打开控制台看一下 console 面板有没有报错，以及 network 中有没没有请求，然后贴图来看一下

**Comment by zsakvo** [comment]
> ![火狐截图_2020-08-06T05-13-35 672Z](https://user-images.githubusercontent.com/20376895/89493465-ce312a80-d7e6-11ea-8f7e-b2f5957568f8.png)
> 
> 你好，我在登陆的时候都么有问题，只是【正在获取章节内容】的时候就卡住不动了，请问这是什么原因？

网页右键，打开控制台看一下 console 面板有没有报错，以及 network 中有没没有请求，然后贴图来看一下

**Comment by chenshunji** [comment]
【console】 没有报错，不过有两个警告
![2020-08-06_134616](https://user-images.githubusercontent.com/20376895/89495898-d8a1f300-d7eb-11ea-95a1-be8c763c0283.jpg)

【network】这里有44个请求
![2020-08-06_134649](https://user-images.githubusercontent.com/20376895/89495824-adb79f00-d7eb-11ea-8914-9938637d8a8b.jpg)

**Comment by chenshunji** [comment]
![2020-08-06_134616](https://user-images.githubusercontent.com/20376895/89496021-1b63cb00-d7ec-11ea-88c6-efe9350e5f28.jpg)
![2020-08-06_134649](https://user-images.githubusercontent.com/20376895/89496026-1e5ebb80-d7ec-11ea-85cc-348f44c22f09.jpg)

**Comment by zsakvo** [comment]
> 【console】 没有报错，不过有两个警告
> ![2020-08-06_134616](https://user-images.githubusercontent.com/20376895/89495898-d8a1f300-d7eb-11ea-95a1-be8c763c0283.jpg)
> 
> 【network】这里有 44 个请求
> ![2020-08-06_134649](https://user-images.githubusercontent.com/20376895/89495824-adb79f00-d7eb-11ea-8914-9938637d8a8b.jpg)

嗯 我测一下看看的

**Comment by zsakvo** [comment]
`Chrome  84.0.4147.105` 未能复现，目测是后台执行 worker 的时候卡住了，FireFox 我没进行过测试，无法保障。你也可以卡住后刷新页面多试几次。这部分逻辑并不完善，后面我会把该功能移植到 Cirno 项目中，所以这边就先不更新了。总之感谢反馈 :)

**Comment by chenshunji** [comment]
那我再使用Chrome试一下吧，感谢了，期待后续的功能~

**Comment by zsakvo** [comment]
本仓库准备废弃，全新构建的版本在此。
https://github.com/zsakvo/Cirno-go
