### ISSUE TITLE
会一直卡在【正在获取章节内容】

### ISSUE THREAD

**Issue by kepler0308** [zsakvo/hbooker-extractor#7]
Chrome版本85.0.4183.83

**Comment by zsakvo** [comment]
提供一下小说名，我看下是不是有无效章节导致的

**Comment by kepler0308** [comment]
小说名：石上真男人只想打游戏

**Comment by zsakvo** [comment]
尝试过滤了一下无效章节，但是依旧是无法复现这个问题。如果再出现可以打开控制台给我看下打印的信息

**Comment by kepler0308** [comment]
你是指cmd控制台吗？
正在启动服务……
启动成功，监听端口：9612
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""
[HPM] Proxy created: /  -> https://app.hbooker.com
[HPM] Proxy rewrite rule created: "^/api" ~> ""

**Comment by zsakvo** [comment]
浏览器，右键，检查，选择 console 选项卡
![image](https://user-images.githubusercontent.com/25399519/91926066-fd18be80-ed08-11ea-8752-3c8b49d4c27c.png)

**Comment by kepler0308** [comment]
<img width="466" alt="微信截图_20200902104516" src="https://user-images.githubusercontent.com/21030232/91926287-862ff580-ed09-11ea-90f9-809f4a17b779.png">

**Comment by zsakvo** [comment]
就这些么？代码更新没？刚才我推了一部分新的。

**Comment by kepler0308** [comment]
只有这些，我刷新了页面，没有出现新的提示，

我是早上把代码下载到本地的，有新的更新吗？

**Comment by zsakvo** [comment]
![image](https://user-images.githubusercontent.com/25399519/91926846-c348b780-ed0a-11ea-941e-022166ff1b86.png)

**Comment by kepler0308** [comment]
<img width="247" alt="微信截图_20200902111407" src="https://user-images.githubusercontent.com/21030232/91928230-153f0c80-ed0e-11ea-90c1-7ae5fa52d86d.png">

**Comment by zsakvo** [comment]
还卡？

**Comment by kepler0308** [comment]
对，还会卡住，你可以成功下载吗？大概要多久?

**Comment by zsakvo** [comment]
可以，大概一秒一章的速度
具体我再看看吧，很迷惑的一个问题
如果你用的 Node 版本较低可以考虑升级到 12 试试

**Comment by kepler0308** [comment]
node版本是12.6.0，之前学习react native安装的

**Comment by kepler0308** [comment]
看到你更新了所以又试了一下，仍然会卡住，然后报这个错误0.0
<img width="473" alt="微信截图_20200908092006" src="https://user-images.githubusercontent.com/21030232/92424229-545dd980-f1b6-11ea-9d9d-3b856871c0f2.png">

**Comment by zsakvo** [comment]
ok 我看一下 有点头绪了

**Comment by zsakvo** [comment]
本仓库准备废弃，全新构建的版本在此。
https://github.com/zsakvo/Cirno-go
